[build-system] # let's go with the default build system (instead of setuptools)
requires = ["hatchling"]
build-backend = "hatchling.build"

[project] # define name = ..., version = 0.0.1 (or whatever you want), dependencies = [...] (rdkit is the only one, in this package)
name = 'acidity_comparison'
version=0.0.1
dependencies = [
  "rdkit", "pandas", "PubChemPy", "request"
]
description='package that receives a list of molecule names and returns their SVG representation and a sorted list of their pKas '
